version: '3.7'

services:
  aws:
    image: amazon/aws-cli
    volumes:
      - .:/code
      - aws-creds:/root/.aws
    restart: 'no'
    working_dir: /code

  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - .:/code
      - aws-creds:/root/.aws
    working_dir: /code
    environment:
      AWS_PROFILE: terraform-operator

  kubectl:
    image: abdennour/kubectl:v1.14.7-aws1.16.277
    volumes:
      - .:/codes
      - aws-creds:/root/.aws:ro
    restart: 'no'
    entrypoint: kubectl
    environment:
      AWS_PROFILE: terraform-operator
      KUBECONFIG: ~/.kube/config
volumes:
  aws-creds:
    name: aws-creds
