version: '3.7'

services:
  aws:
    image: amazon/aws-cli
    volumes:
      - .:/code
      - aws-creds:/root/.aws
    restart: 'no'
    working_dir: /code

  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - .:/code
      - aws-creds:/root/.aws
    working_dir: /code
    environment:
      AWS_PROFILE: terraform-operator

volumes:
  aws-creds:
    name: aws-creds
