repositories:
  - name: nginx-stable
    url: https://helm.nginx.com/stable

helmDefaults:
  tillerless: true
  verify: false
  wait: true
  timeout: 600
  force: true

releases:
  - name: ingress
    chart: nginx-stable/nginx-ingress
    version: 2.3.0
    namespace: kube-system
    values:
      - './charts/nginx-ingress/values.yaml'
  - name: jenkins
    chart: stable/jenkins
    namespace: cicd
    values:
      - './charts/jenkins/values.yaml'

set:
  - name: jenkinsadminPassword
    value: { { requiredEnv "JENKINS_PWD" } }
