persistence:
  enabled: true
  size: '3Gi'

master:
  tag: 'lts'
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName:
    jenkinsUrl: ''
    adminPassword: HelloWorld
